version: "3.9"

services:
  # Banco de dados
  auth_app_database:
    image: postgres
    container_name: auth_app_database
    restart: always
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASS}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - pgdata:/data/postgres

  # Aplicação
  auth_app_api:
    build: .
    container_name: auth_app_api
    restart: always
    ports:
      - ${APP_PORT}:3333
      - 9229:9229
    volumes:
      - .:/usr/app
    depends_on:
      - auth_app_database
    links:
      - auth_app_database

volumes:
  pgdata:
    driver: local
