version: "3.9"

services:

  # Database
  auth_flow_database:
    image: postgres
    container_name: auth_flow_database
    restart: always
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASS}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - pgdata:/data/postgres

  # Application
  auth_flow_api:
    build: .
    container_name: auth_flow_api
    restart: always
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - .:/usr/app
    depends_on:
      - auth_flow_database
    links:
      - auth_flow_database

volumes:
  pgdata:
    driver: local
