version: "3.9"

services:
  # Banco de dados
  database_authentication_app:
    image: postgres
    container_name: database_authentication_app
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=authentication_app
      - POSTGRES_DB=authentication_app
    volumes:
      - pgdata:/data/postgres

  # Aplicação
  app:
    build: .
    container_name: authentication_app
    restart: always
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/app
    links:
      - database_authentication_app
    depends_on:
      - database_authentication_app

volumes:
  pgdata:
    driver: local
